spring.application.name=job-recruitment-system
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/job_platform_db?useUnicode=true&characterEncoding=UTF-8

spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u h\uFFFDnh Mail Server (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22T1020756@husc.edu.vn
spring.mail.password=bxkvwtkyqefrfuuh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CLOUDINARY CONFIG ---
cloudinary.cloud-name=dzztoxy1d
cloudinary.api-key=941752399185154
cloudinary.api-secret=fud2hp3-7uzS9FFcin-YhGJxVWQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

jwt.secret=${JWT_SECRET:wGsbnPNOEbDFV7FmJ1DokVP4QojQpwNjrF7DghJo59o=}
# 15 ph\uFFFDt (900,000 ms)
jwt.expiration=900000
# 7 ng\uFFFDy (604,800,000 ms)
jwt.refresh-expiration=604800000

# C?u h\uFFFDnh Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

google.client.id=903060944543-5puelt4lrg6eh659rnoms38bbq7h1p7o.apps.googleusercontent.com

spring.jackson.property-naming-strategy=SNAKE_CASE

login.max-attempts=3
login.lock-time-seconds=900

login.attempt.max=3
login.attempt.lock-minutes=15
google.recaptcha.secret=6LdsswItAAAAABsaWQRdN-W3pg7N3WquyDMYa_tg
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
vnpay.tmnCode=MWV3XMZ7
vnpay.hashSecret=9W96NI1GPG8XMYW5TBEOEWOS76135PVG
vnpay.returnUrl=https://api.pathuongdev.id.vn/api/payment/vnpay-return
vnpay.vnp_PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.version=2.1.0
vnpay.command=pay